# Generated by Django 2.1.7 on 2019-02-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketForm',
            new_name='Model',
        ),
    ]
